apiVersion: v1
kind: Service
metadata:
  labels:
    component: dmz-apiserver-etcd
    tier: control-plane
  name: dmz-apiserver-etcd
spec:
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
    name: etcd 
  - port: 2380
    protocol: TCP
    targetPort: 2380
    name: peer 
  selector:
    component: dmz-apiserver-etcd
    tier: control-plane
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: True
