apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.kubermatic.jw.io
spec:
  group: kubermatic.jw.io
  groupPriorityMinimum: 1
  insecureSkipTLSVerify: false
  service:
    name: dmz-apiserver
    namespace: jw-api-test
  version: v1
  versionPriority: 1
