apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cluster-hack
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cluster-wh-webhook
      namespace: jw-hack-cluster
      path: /mutate-cluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: cluster-wh.kubermatic.jw.io
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - kubermatic.jw.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - dmzclusters
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
