
apiVersion: v1
kind: Service
metadata:
  name: cluster-wh-webhook
spec:
  ports:
    - port: 9443
      targetPort: validating-hook
      protocol: TCP
  selector:
    control-plane: cluster-wh
  type: ClusterIP
