---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-wh
rules:
- apiGroups:
  - "kubermatic.k8s.io"
  - "kubermatic.jw.io"
  resources:
  - clusters
  - dmzclusters
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
  - delete
