apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cluster-wh-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-wh-webhook-serving-cert
spec:
  commonName: $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  dnsNames:
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
  issuerRef:
    kind: Issuer
    name: cluster-wh-selfsigned-issuer
  secretName: cluster-wh-admission-webhook-tls
  isCA: true
  duration: 17088h #(24*356*2)h = 2years
  renewBefore: 744h #(24*31)h = 1month
