//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	kubermaticv1 "k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.Cloud.DeepCopyInto(&out.Cloud)
	if in.MachineNetworks != nil {
		in, out := &in.MachineNetworks, &out.MachineNetworks
		*out = make([]kubermaticv1.MachineNetworkingConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OIDC = in.OIDC
	if in.UpdateWindow != nil {
		in, out := &in.UpdateWindow, &out.UpdateWindow
		*out = new(kubermaticv1.UpdateWindow)
		**out = **in
	}
	if in.EnableUserSSHKeyAgent != nil {
		in, out := &in.EnableUserSSHKeyAgent, &out.EnableUserSSHKeyAgent
		*out = new(bool)
		**out = **in
	}
	if in.PodNodeSelectorAdmissionPluginConfig != nil {
		in, out := &in.PodNodeSelectorAdmissionPluginConfig, &out.PodNodeSelectorAdmissionPluginConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdmissionPlugins != nil {
		in, out := &in.AdmissionPlugins, &out.AdmissionPlugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuditLogging != nil {
		in, out := &in.AuditLogging, &out.AuditLogging
		*out = new(kubermaticv1.AuditLoggingSettings)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(kubermaticv1.ServiceAccountSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.OPAIntegration != nil {
		in, out := &in.OPAIntegration, &out.OPAIntegration
		*out = new(kubermaticv1.OPAIntegrationSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.MLA != nil {
		in, out := &in.MLA, &out.MLA
		*out = new(kubermaticv1.MLASettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterNetwork != nil {
		in, out := &in.ClusterNetwork, &out.ClusterNetwork
		*out = new(kubermaticv1.ClusterNetworkingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DMZCluster) DeepCopyInto(out *DMZCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DMZCluster.
func (in *DMZCluster) DeepCopy() *DMZCluster {
	if in == nil {
		return nil
	}
	out := new(DMZCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DMZCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DMZClusterList) DeepCopyInto(out *DMZClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DMZCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DMZClusterList.
func (in *DMZClusterList) DeepCopy() *DMZClusterList {
	if in == nil {
		return nil
	}
	out := new(DMZClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DMZClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
